# Generated by Django 6.0.4 on 2026-04-28 07:16

import django.core.validators
import django.db.models.deletion
import quotation.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paints', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=quotation.models._next_quotation_reference, editable=False, max_length=20, unique=True, verbose_name='reference')),
                ('customer_name', models.CharField(max_length=200, verbose_name='customer name')),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='customer email')),
                ('customer_phone', models.CharField(blank=True, default='', max_length=30, verbose_name='customer phone')),
                ('project_name', models.CharField(blank=True, default='', max_length=200, verbose_name='project name')),
                ('project_location', models.CharField(blank=True, default='', max_length=300, verbose_name='project location')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=10, verbose_name='status')),
                ('subtotal_excl_vat', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='subtotal (excl. VAT)')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='VAT amount')),
                ('total_incl_vat', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total (incl. VAT)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'quotation',
                'verbose_name_plural': 'quotations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substrate_type', models.CharField(choices=[('INTERIOR', 'Interior'), ('EXTERIOR', 'Exterior')], default='INTERIOR', max_length=10, verbose_name='substrate type')),
                ('subsection_key', models.CharField(max_length=80, verbose_name='subsection key')),
                ('display_name', models.CharField(max_length=120, verbose_name='display name')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='sort order')),
                ('is_placeholder', models.BooleanField(default=False, verbose_name='is placeholder')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='quotation.quotation', verbose_name='quotation')),
            ],
            options={
                'verbose_name': 'quotation section',
                'verbose_name_plural': 'quotation sections',
                'ordering': ['quotation', 'sort_order', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='QuotationLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('PAINT', 'Paint'), ('PREP_WORK', 'Prep Work'), ('PRIMER', 'Primer'), ('WATERPROOFING', 'Waterproofing'), ('NOTE', 'Note / Comment')], db_index=True, default='PAINT', max_length=20, verbose_name='item type')),
                ('description', models.TextField(verbose_name='description')),
                ('coats', models.PositiveSmallIntegerField(default=1, verbose_name='coats')),
                ('area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='area (m²)')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='quantity')),
                ('unit', models.CharField(blank=True, default='', max_length=30, verbose_name='unit')),
                ('price_excl_vat', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='unit price (excl. VAT)')),
                ('price_incl_vat', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='unit price (incl. VAT)')),
                ('total_excl_vat', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='line total (excl. VAT)')),
                ('total_incl_vat', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='line total (incl. VAT)')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('paint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_line_items', to='paints.paint', verbose_name='paint')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='quotation.quotation', verbose_name='quotation')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_items', to='quotation.quotationsection', verbose_name='section')),
            ],
            options={
                'verbose_name': 'quotation line item',
                'verbose_name_plural': 'quotation line items',
                'ordering': ['quotation', 'section__sort_order', 'pk'],
            },
        ),
    ]
