# Generated by Django 6.0.4 on 2026-05-16 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationPdfExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_key', models.CharField(max_length=50, verbose_name='template key')),
                ('file', models.FileField(blank=True, null=True, upload_to='quotation_pdfs/', verbose_name='PDF file')),
                ('status', models.CharField(choices=[('GENERATED', 'Generated'), ('FAILED', 'Failed')], default='GENERATED', max_length=10, verbose_name='status')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='error message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_exports', to=settings.AUTH_USER_MODEL, verbose_name='generated by')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_exports', to='quotation.quotation', verbose_name='quotation')),
            ],
            options={
                'verbose_name': 'quotation PDF export',
                'verbose_name_plural': 'quotation PDF exports',
                'ordering': ['-created_at'],
            },
        ),
    ]
