# Generated by Django 6.0.4 on 2026-05-31 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0002_quotationpdfexport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='quotation.quotation', verbose_name='quotation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_pins', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'quotation pin',
                'verbose_name_plural': 'quotation pins',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'quotation')},
            },
        ),
    ]
