# Generated by Django 6.0.4 on 2026-05-16 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRepProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, default='', max_length=500, verbose_name='bio')),
                ('job_title', models.CharField(blank=True, default='', max_length=100, verbose_name='job title')),
                ('department', models.CharField(blank=True, default='', max_length=100, verbose_name='department')),
                ('branch_location', models.CharField(blank=True, default='', max_length=100, verbose_name='branch / office location')),
                ('company_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='company phone')),
                ('whatsapp_number', models.CharField(blank=True, default='', max_length=20, verbose_name='WhatsApp number')),
                ('business_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='business email')),
                ('sales_region', models.CharField(blank=True, default='', max_length=100, verbose_name='sales region')),
                ('employee_code', models.CharField(blank=True, default='', max_length=30, verbose_name='employee code')),
                ('years_experience', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='years of experience')),
                ('specialities', models.TextField(blank=True, default='', max_length=300, verbose_name='specialities')),
                ('default_quote_intro', models.TextField(blank=True, default='', help_text='Introductory text auto-filled on new quotations.', max_length=1000, verbose_name='default quote intro')),
                ('default_quote_footer', models.TextField(blank=True, default='', help_text='Footer / closing text auto-filled on new quotations.', max_length=1000, verbose_name='default quote footer')),
                ('signature_name', models.CharField(blank=True, default='', max_length=150, verbose_name='signature name')),
                ('signature_title', models.CharField(blank=True, default='', max_length=100, verbose_name='signature title')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sales rep profile',
                'verbose_name_plural': 'sales rep profiles',
            },
        ),
        migrations.CreateModel(
            name='UserAppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appearance', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System Default')], default='light', max_length=10, verbose_name='appearance')),
                ('accent_style', models.CharField(choices=[('prostar_default', 'ProStar Default (Purple)'), ('green', 'Green'), ('high_contrast', 'High Contrast')], default='prostar_default', max_length=20, verbose_name='accent style')),
                ('table_density', models.CharField(choices=[('comfortable', 'Comfortable'), ('compact', 'Compact')], default='comfortable', max_length=15, verbose_name='table density')),
                ('default_dashboard_period', models.CharField(choices=[('all_time', 'All Time'), ('this_month', 'This Month'), ('last_30_days', 'Last 30 Days')], default='last_30_days', max_length=15, verbose_name='default dashboard period')),
                ('rows_per_page', models.PositiveSmallIntegerField(choices=[(10, '10'), (25, '25'), (50, '50')], default=25, verbose_name='rows per page')),
                ('builder_summary_default', models.CharField(choices=[('expanded', 'Expanded'), ('collapsed', 'Collapsed')], default='expanded', max_length=10, verbose_name='builder summary default')),
                ('reduce_animations', models.BooleanField(default=False, verbose_name='reduce animations')),
                ('show_watermark', models.BooleanField(default=True, verbose_name='show watermark')),
                ('show_help_text', models.BooleanField(default=True, verbose_name='show help text')),
                ('email_notifications_enabled', models.BooleanField(default=False, verbose_name='email notifications enabled')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user app settings',
                'verbose_name_plural': 'user app settings',
            },
        ),
    ]
