# Generated by Django 6.0.4 on 2026-05-31 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_salesrepprofile_userappsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userappsettings',
            name='auto_collapse_builder_summary_mobile',
            field=models.BooleanField(default=False, verbose_name='auto-collapse builder summary on mobile'),
        ),
        migrations.AddField(
            model_name='userappsettings',
            name='compact_navigation',
            field=models.BooleanField(default=False, verbose_name='compact navigation'),
        ),
        migrations.AddField(
            model_name='userappsettings',
            name='default_landing_page',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('quotations', 'Quotations list'), ('new_quotation', 'New quotation'), ('profile', 'Profile')], default='dashboard', max_length=20, verbose_name='default landing page'),
        ),
        migrations.AddField(
            model_name='userappsettings',
            name='default_quotation_sort',
            field=models.CharField(choices=[('updated_desc', 'Recently updated'), ('created_desc', 'Recently created'), ('customer_asc', 'Customer (A → Z)')], default='updated_desc', max_length=20, verbose_name='default quotation sort'),
        ),
        migrations.AddField(
            model_name='userappsettings',
            name='high_contrast_mode',
            field=models.BooleanField(default=False, verbose_name='high contrast mode'),
        ),
        migrations.AddField(
            model_name='userappsettings',
            name='larger_text',
            field=models.BooleanField(default=False, verbose_name='larger text'),
        ),
        migrations.AddField(
            model_name='userappsettings',
            name='notify_draft_quotations',
            field=models.BooleanField(default=True, verbose_name='notify about draft quotations'),
        ),
        migrations.AddField(
            model_name='userappsettings',
            name='notify_failed_pdfs',
            field=models.BooleanField(default=True, verbose_name='notify about failed PDF exports'),
        ),
        migrations.AddField(
            model_name='userappsettings',
            name='notify_placeholder_sections',
            field=models.BooleanField(default=True, verbose_name='notify about placeholder quotation sections'),
        ),
        migrations.AddField(
            model_name='userappsettings',
            name='notify_profile_incomplete',
            field=models.BooleanField(default=True, verbose_name='notify when profile is incomplete'),
        ),
        migrations.AddField(
            model_name='userappsettings',
            name='notify_system_activity',
            field=models.BooleanField(default=True, verbose_name='notify about system activity (admins)'),
        ),
        migrations.AddField(
            model_name='userappsettings',
            name='preferred_pdf_template',
            field=models.CharField(choices=[('professional', 'Professional'), ('detailed_spec', 'Detailed Specification'), ('compact', 'Compact Estimate')], default='professional', max_length=30, verbose_name='preferred PDF template'),
        ),
        migrations.AddField(
            model_name='userappsettings',
            name='preferred_quotation_view',
            field=models.CharField(choices=[('table', 'Table'), ('cards', 'Cards')], default='table', max_length=10, verbose_name='preferred quotation view'),
        ),
        migrations.AddField(
            model_name='userappsettings',
            name='remember_last_pdf_template',
            field=models.BooleanField(default=True, verbose_name='remember last PDF template used'),
        ),
        migrations.AddField(
            model_name='userappsettings',
            name='show_builder_help_tips',
            field=models.BooleanField(default=True, verbose_name='show builder help tips'),
        ),
        migrations.AddField(
            model_name='userappsettings',
            name='show_command_palette_hint',
            field=models.BooleanField(default=True, verbose_name='show command palette hint button'),
        ),
        migrations.AddField(
            model_name='userappsettings',
            name='show_data_quality_widget',
            field=models.BooleanField(default=True, verbose_name='show data quality widget'),
        ),
        migrations.AddField(
            model_name='userappsettings',
            name='show_draft_quotations_widget',
            field=models.BooleanField(default=True, verbose_name='show draft quotations widget'),
        ),
        migrations.AddField(
            model_name='userappsettings',
            name='show_onboarding_checklist',
            field=models.BooleanField(default=True, verbose_name='show onboarding checklist'),
        ),
        migrations.AddField(
            model_name='userappsettings',
            name='show_quick_actions_fab',
            field=models.BooleanField(default=True, verbose_name='show floating quick-actions button'),
        ),
        migrations.AddField(
            model_name='userappsettings',
            name='show_recent_activity_widget',
            field=models.BooleanField(default=True, verbose_name='show recent activity widget'),
        ),
    ]
