# Generated by Django 6.0.4 on 2026-04-28 03:47

import django.core.validators
import django.db.models.deletion
import invoices.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=invoices.models._next_invoice_reference, editable=False, max_length=20, unique=True, verbose_name='reference')),
                ('customer_name', models.CharField(max_length=200, verbose_name='customer name')),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='customer email')),
                ('customer_phone', models.CharField(blank=True, default='', max_length=30, verbose_name='customer phone')),
                ('project_name', models.CharField(blank=True, default='', max_length=200, verbose_name='project name')),
                ('project_location', models.CharField(blank=True, default='', max_length=300, verbose_name='project location')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=10, verbose_name='status')),
                ('subtotal_excl_vat', models.DecimalField(decimal_places=2, default='0.00', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='subtotal (excl. VAT)')),
                ('vat_amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='VAT amount')),
                ('total_incl_vat', models.DecimalField(decimal_places=2, default='0.00', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total (incl. VAT)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('is_removed', models.BooleanField(db_index=True, default=False, verbose_name='removed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'invoice',
                'verbose_name_plural': 'invoices',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='invoices_in_created_67cbdc_idx'), models.Index(fields=['created_by'], name='invoices_in_created_cd483a_idx'), models.Index(fields=['status'], name='invoices_in_status_cec546_idx')],
            },
        ),
    ]
