# Generated by ChatGPT - add knowledge fields migration
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specifications", "0006_create_manualspecificationdraft"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgeentry",
            name="priority",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="knowledgeentry",
            name="tags",
            field=models.JSONField(default=list, blank=True),
        ),
        migrations.AddField(
            model_name="knowledgeentry",
            name="metadata",
            field=models.JSONField(default=dict, blank=True),
        ),
    ]
