# Generated by Django 6.0.4 on 2026-08-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specifications', '0007_add_knowledge_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualspecificationdraft',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
