# Generated by Django 6.0.4 on 2026-09-04 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specifications', '0008_alter_manualspecificationdraft_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurfaceDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_section', models.CharField(choices=[('INTERIOR', 'Interior'), ('EXTERIOR', 'Exterior')], db_index=True, max_length=20)),
                ('subsection', models.CharField(db_index=True, max_length=120)),
                ('surface', models.CharField(db_index=True, max_length=120)),
                ('preparation_requirements', models.TextField(blank=True)),
                ('surface_rules', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Surface Default',
                'verbose_name_plural': 'Surface Defaults',
                'ordering': ['main_section', 'subsection', 'surface'],
                'unique_together': {('main_section', 'subsection', 'surface')},
            },
        ),
    ]
