# Generated by Django 6.0.4 on 2026-09-07 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0007_quotationsectionimage'),
        ('specifications', '0009_surfacedefault'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualSpecificationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preparation_requirements', models.TextField(blank=True, default='')),
                ('application_requirements', models.TextField(blank=True, default='')),
                ('images', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_specification_items', to='quotation.quotation')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_specification_items', to='quotation.quotationsection')),
            ],
            options={
                'verbose_name': 'Manual Specification Item',
                'verbose_name_plural': 'Manual Specification Items',
                'ordering': ['section__sort_order', 'section__pk', 'pk'],
                'unique_together': {('quotation', 'section')},
            },
        ),
    ]
