# Generated by Django 6.0.4 on 2026-09-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specifications', '0010_manualspecificationitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualspecificationitem',
            name='original_application_requirements',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='manualspecificationitem',
            name='original_preparation_requirements',
            field=models.TextField(blank=True, default=''),
        ),
    ]
