# Generated by Django 6.0.4 on 2026-04-28 03:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('category', models.CharField(choices=[('INTERIOR', 'Interior'), ('EXTERIOR', 'Exterior'), ('PRIMER', 'Primer'), ('WATERPROOFING', 'Waterproofing'), ('TEXTURE', 'Texture'), ('SPECIALIST', 'Specialist')], default='INTERIOR', max_length=20, verbose_name='category')),
                ('paint_type', models.CharField(choices=[('WATER_BASED', 'Water Based'), ('SOLVENT_BASED', 'Solvent Based'), ('ENAMEL', 'Enamel'), ('ACRYLIC', 'Acrylic'), ('OIL_BASED', 'Oil Based'), ('EPOXY', 'Epoxy'), ('OTHER', 'Other')], default='WATER_BASED', max_length=20, verbose_name='paint type')),
                ('base_type', models.CharField(choices=[('WHITE', 'White'), ('PASTEL', 'Pastel Base'), ('MEDIUM', 'Medium Base'), ('DEEP', 'Deep Base'), ('CLEAR', 'Clear Base'), ('TRANSPARENT', 'Transparent Base'), ('NATURAL', 'Natural'), ('NOT_APPLICABLE', 'Not Applicable')], default='WHITE', max_length=20, verbose_name='base type')),
                ('colour', models.CharField(blank=True, default='', max_length=100, verbose_name='colour')),
                ('price_excl_vat', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price (excl. VAT)')),
                ('price_incl_vat', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price (incl. VAT)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='paints/images/', verbose_name='product image')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'paint',
                'verbose_name_plural': 'paints',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['category'], name='paints_pain_categor_77c8b0_idx'), models.Index(fields=['is_active'], name='paints_pain_is_acti_505184_idx')],
            },
        ),
    ]
