"""
Generated by hand for Pricing Pack 1A: add finish, spread_rate_per_litre, priced_volume_litres
"""
from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paints", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paint",
            name="finish",
            field=models.CharField(
                verbose_name='finish',
                max_length=30,
                choices=[
                    ("SMOOTH_MATTE", "Smooth Matte"),
                    ("SMOOTH_SHEEN", "Smooth Sheen"),
                    ("DECO_PLAST", "Deco-plast"),
                    ("FINE_TEXTURE", "Fine Texture"),
                    ("COARSE_TEXTURE", "Coarse Texture"),
                    ("NOT_APPLICABLE", "Not Applicable"),
                ],
                null=True,
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="paint",
            name="spread_rate_per_litre",
            field=models.DecimalField(
                verbose_name='spread rate (m² per litre)',
                null=True,
                blank=True,
                max_digits=7,
                decimal_places=2,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AddField(
            model_name="paint",
            name="priced_volume_litres",
            field=models.DecimalField(
                verbose_name='priced volume (litres)',
                max_digits=7,
                decimal_places=2,
                default=Decimal("1.00"),
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
    ]
