# Generated by Django 6.0.4 on 2026-08-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paints', '0005_add_group_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='paint',
            name='application_method',
            field=models.CharField(blank=True, default='', help_text='Primary application method used by this product in the specification report.', max_length=80, verbose_name='default application method'),
        ),
        migrations.AddField(
            model_name='paint',
            name='application_methods',
            field=models.JSONField(blank=True, default=list, help_text='Optional structured list of method-specific notes and technical values such as spray, roller or brush.', verbose_name='application methods'),
        ),
        migrations.AddField(
            model_name='paint',
            name='dft_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum dry film thickness in microns.', max_digits=6, null=True, verbose_name='DFT maximum'),
        ),
        migrations.AddField(
            model_name='paint',
            name='dft_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum dry film thickness in microns.', max_digits=6, null=True, verbose_name='DFT minimum'),
        ),
        migrations.AddField(
            model_name='paint',
            name='drying_time',
            field=models.CharField(blank=True, default='', help_text='Typical drying time guidance for the selected product.', max_length=120, verbose_name='drying time'),
        ),
        migrations.AddField(
            model_name='paint',
            name='recoat_time',
            field=models.CharField(blank=True, default='', help_text='Typical recoat window guidance for the selected product.', max_length=120, verbose_name='recoat time'),
        ),
        migrations.AddField(
            model_name='paint',
            name='tds_reference',
            field=models.CharField(blank=True, default='', help_text='Reference code or document number for the product technical data sheet.', max_length=200, verbose_name='TDS reference'),
        ),
        migrations.AddField(
            model_name='paint',
            name='tds_revision',
            field=models.CharField(blank=True, default='', help_text='Optional revision number or issue code for the TDS.', max_length=50, verbose_name='TDS revision'),
        ),
        migrations.AddField(
            model_name='paint',
            name='tds_url',
            field=models.URLField(blank=True, default='', help_text='Optional web link or document URL for the product technical data sheet.', max_length=500, verbose_name='TDS URL'),
        ),
        migrations.AlterField(
            model_name='paint',
            name='group_key',
            field=models.CharField(blank=True, help_text='Machine key linking this product to a PAINT_GROUPS entry for UI grouping', max_length=50, null=True, verbose_name='group key'),
        ),
    ]
