# Generated by Django 6.0.4 on 2026-04-28 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemToolRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=100, verbose_name='tool name')),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('ERROR', 'Error')], db_index=True, default='SUCCESS', max_length=10, verbose_name='status')),
                ('summary', models.TextField(verbose_name='summary')),
                ('result_data', models.JSONField(blank=True, null=True, verbose_name='result data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('run_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_tool_runs', to=settings.AUTH_USER_MODEL, verbose_name='run by')),
            ],
            options={
                'verbose_name': 'system tool run',
                'verbose_name_plural': 'system tool runs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='system_tool_created_06ea21_idx'), models.Index(fields=['tool_name'], name='system_tool_tool_na_7b79c4_idx')],
            },
        ),
    ]
