# Generated by Django 6.0.4 on 2026-04-28 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_tools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, help_text='Unique identifier for this setting, e.g. VAT_RATE', max_length=100, unique=True, verbose_name='key')),
                ('value', models.CharField(help_text='String representation of the setting value', max_length=500, verbose_name='value')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setting_updates', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'app setting',
                'verbose_name_plural': 'app settings',
                'ordering': ['key'],
            },
        ),
    ]
