# Generated by Django 6.0.4 on 2026-04-28 05:37

from django.db import migrations


def seed_vat_rate(apps, schema_editor):
    """Insert the default VAT rate of 15% if not already present."""
    AppSetting = apps.get_model("system_tools", "AppSetting")
    AppSetting.objects.get_or_create(
        key="VAT_RATE",
        defaults={
            "value": "15.00",
            "description": "Application VAT rate as a percentage (e.g. 15.00 = 15%).",
        },
    )


def remove_vat_rate(apps, schema_editor):
    AppSetting = apps.get_model("system_tools", "AppSetting")
    AppSetting.objects.filter(key="VAT_RATE").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("system_tools", "0002_appsetting_model"),
    ]

    operations = [
        migrations.RunPython(seed_vat_rate, remove_vat_rate),
    ]
