# Generated by Django 6.0.4 on 2026-05-31 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_tools', '0003_seed_vat_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='ProStar Paints', max_length=120, verbose_name='company name')),
                ('company_tagline', models.CharField(blank=True, default='', max_length=200, verbose_name='tagline')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='logo')),
                ('primary_colour', models.CharField(blank=True, default='', max_length=7, verbose_name='primary colour')),
                ('accent_colour', models.CharField(blank=True, default='', max_length=7, verbose_name='accent colour')),
                ('support_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='support email')),
                ('support_phone', models.CharField(blank=True, default='', max_length=40, verbose_name='support phone')),
                ('website', models.URLField(blank=True, default='', verbose_name='website')),
                ('pdf_footer_note', models.CharField(blank=True, default='', max_length=300, verbose_name='PDF footer note')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branding_updates', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'branding setting',
                'verbose_name_plural': 'branding settings',
            },
        ),
    ]
