# Generated by Django 6.0.4 on 2026-09-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_tools', '0004_brandingsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingsetting',
            name='pdf_footer_image',
            field=models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='PDF footer image'),
        ),
        migrations.AddField(
            model_name='brandingsetting',
            name='pdf_header_image',
            field=models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='PDF header image'),
        ),
    ]
